workspace:
  base: /go
  path: src/github.com/kgantsov/kvgo

pipeline:
  tests:
    image: golang:latest
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure --vendor-only
      - go test ./... -race
    when:
      event: [ push ]

pipeline:
  slack:
    image: plugins/slack
    channel: dev
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
